# Generated by Django 2.2.7 on 2019-11-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=30, verbose_name='CUSTOMER ID')),
                ('customer_type', models.CharField(max_length=20, verbose_name='CUSTOMER TYPE')),
                ('birth_year', models.SmallIntegerField(verbose_name='BIRTH YEAR')),
                ('birth_month', models.SmallIntegerField(verbose_name='BIRTH MONTH')),
                ('province', models.CharField(max_length=20, verbose_name='')),
                ('city', models.CharField(max_length=20, verbose_name='CITY')),
                ('district', models.CharField(max_length=20, verbose_name='DISTRICT')),
                ('gender', models.CharField(max_length=20, verbose_name='GENDER')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=30, verbose_name='CUSTOMER ID')),
                ('sales_type', models.CharField(max_length=20, verbose_name='SALES TYPE')),
                ('contract_type', models.CharField(max_length=20, verbose_name='CONTRACT TYPE')),
                ('distribution_channel', models.CharField(max_length=30, verbose_name='DISTRIBUTION CHANNEL')),
                ('contract_date', models.CharField(max_length=30, verbose_name='CONTRACT DATE')),
                ('contract_period', models.SmallIntegerField(verbose_name='CONTRACT PERIOD')),
                ('payment_type', models.CharField(max_length=20, verbose_name='PAYMENT TYPE')),
                ('product_family', models.CharField(max_length=20, verbose_name='PRODUCT FAMILY')),
                ('rental_cost', models.IntegerField(verbose_name='RENTAL COST')),
                ('contract_status', models.CharField(max_length=20, verbose_name='CONTRACT STATUS')),
                ('num_arrear', models.SmallIntegerField(verbose_name='NUMBER OF ARREAR')),
                ('overdue', models.CharField(max_length=20, verbose_name='OVERDUE')),
                ('credit_rating', models.CharField(max_length=20, verbose_name='CREDIT RATING')),
                ('payment_bank', models.CharField(max_length=20, verbose_name='PAYMENT BANK')),
                ('canceled', models.CharField(max_length=20, verbose_name='CANCELED')),
            ],
        ),
    ]
