# Generated by Django 2.2.7 on 2019-11-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_month',
            field=models.FloatField(verbose_name='BIRTH MONTH'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_year',
            field=models.FloatField(verbose_name='BIRTH YEAR'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='contract_period',
            field=models.FloatField(verbose_name='CONTRACT PERIOD'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='num_arrear',
            field=models.FloatField(verbose_name='NUMBER OF ARREAR'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='rental_cost',
            field=models.FloatField(verbose_name='RENTAL COST'),
        ),
    ]
