# Generated by Django 2.2.7 on 2019-11-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20191108_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.CharField(default=0, max_length=50, verbose_name='AGE'),
            preserve_default=False,
        ),
    ]
